<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Retrace</AssemblyName>
    <RootNamespace>Retrace.App</RootNamespace>
    <ApplicationIcon>Assets\Retrace.ico</ApplicationIcon>
    <Version>0.2.0</Version>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <FileVersion>0.2.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Retrace.Core\Retrace.Core.csproj" />
    <ProjectReference Include="..\Retrace.Data\Retrace.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Retrace.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
